[settings]
provider = "base"

[Sys]
install = [
  "git",
  "curl",
  "wget",
  "base-devel",
  "unzip",
  "tar",
  "7zip",
]

[AUR]
commands = [
  "sudo pacman -S base-devel",
  "git clone https://aur.archlinux.org/paru.git",
  "cd paru",
  "makepkg -si",
  "cd ~",
  "rm -rf ~/paru"
]

[DE]
install = [
  "nvidia",
  "kitty",
  "rofi",
  "niri",
  "labwc",
  "swaync",
  "waybar",
  "wl-clipboard",
  "cliphist",
]
commands = ["sudo usermod -aG input,fprint $USER"]

[Sound]
install =[ 
  "pipewire",
  "wireplumber",
  "pipewire-pulse",
  "pipewire-alsa",
  "pipewire-jack",
  "pavucontrol",
]
commands = ["systemctl --user enable --now pipewire pipewire-pulse wireplumber"]

[QT_and_GTK_Support]
install = [
  "qt5-wayland",
  "qt6-wayland",
  "qt6-svg",
  "qt6-declarative",
  "qt5-quickcontrols2",
  "qt6-5compat",
  "qt5-graphicaleffects",
  "gtk3",
  "gtk4",
  "xdg-desktop-portal",
  "xdg-desktop-portal-gtk",
 ]

[SDDM]
install = ["sddm"]
commands = [
  "sudo systemctl enable sddm.service",
  "sudo systemctl start sddm.service",
]

