[settings]
provider = "base"

[Sys]
install = [
  "git",
  "curl",
  "wget",
  "base-devel",
  "unzip",
  "tar",
  "7zip",
]

[Hyprland]
install = [
  "mesa",
  "kitty",
  "rofi",
  "niri",
  "swaync",
  "wl-clipboard",
  "cliphist",
]
commands = ["sudo usermod -aG input,fprint $USER"]

[Sound]
install =[ 
  "pipewire",
  "pipewire-alsa",
  "pipewire-pulse",
  "pipewire-jack",
  "wireplumber",
]

[QT_and_GTK_Support]
install = [
  "qt5-wayland",
  "qt6-wayland",
  "qt6-svg",
  "qt6-declarative",
  "qt5-quickcontrols2",
  "gtk3",
  "gtk4",
  "xdg-desktop-portal",
  "xdg-desktop-portal-gtk",
 ]

[SDDM]
install = ["sddm"]
commands = [
  "sudo systemctl enable sddm.service",
  "sudo systemctl start sddm.service",
]

