[mgr]
prepend_keymap = [
    ########################
    ## compress with ouch ##
    ########################
    { on = ["C"], run = "plugin ouch", desc = "Compress with ouch" },
    ###########
    ## chmod ##
    ###########
    { on = [ "c", "m" ], run = "plugin chmod", desc = "Chmod on selected files" },

    #############
    ## lazygit ##
    #############
    { on = [ "g", "i" ], run = "plugin lazygit", desc = "run lazygit" },

    ###############
    ## what size ##
    ###############
    { on = [ "w", "s" ], run = "plugin what-size", desc = "Calc size of selection or cwd" },
]

